[versions]
# 依赖版本号
accompanistPlaceholderMaterial = "0.31.0-alpha"

activityVersion = "1.8.2"
appCenterSdkVersion = "5.0.4"
appcompat = "1.6.1"
appcompatV7 = "28.0.0"
atomicfu = "0.22.0"
coilCompose = "2.5.0"
compose = "1.7.0-alpha04"
zoomable = "1.6.0"
compose-compiler = "1.5.4"

constraintlayout = "2.1.4"
coreKtx = "1.12.0"
coreVersion = "3.5.0"
crashx = "v6.0.19"
danmakuflamemaster = "0.9.25"
datastore = "1.0.0"
espressoCoreVersion = "3.0.2"
gson = "2.10.1"
hiltAndroid = "2.50"
hiltWork = "1.2.0"
jsoup = "1.15.4"
runner = "1.0.2"
junitVersion = "4.12"
rxhttp = "3.2.3"
okhttp = "4.12.0"
kotlinxMetadataJvm = "0.7.0"
ktorClientCore = "2.3.7"
lifecycleRuntimeKtx = "2.7.0"
material = "1.11.0"
material3WindowSizeClass = "1.2.1"


media3Exoplayer = "1.3.0"
pagingCompose = "3.2.1"
paletteKtx = "1.0.0"


compileSdk = "34"
jvm-target = "17"
photoview = "2.3.0"
protobuflite = "3.25.1"
protobuf = "0.9.4"
room = "2.6.1"
targetSdk = "34"
buildTool = "34.0.0"
minSdk = "21"

agp = "8.2.2"

kotlin = "1.9.23"
workRuntime = "2.9.0"
ksp = "1.9.22-1.0.16"
junit = "1.1.5"
espressoCore = "3.5.1"
uiautomator = "2.3.0"
benchmarkMacroJunit4 = "1.2.3"
baselineprofile = "1.2.3"
profileinstaller = "1.3.1"

leancloud = "8.2.19"
rxjava = "2.1.1"

ijkplayer = "0.8.8"
bilibili-sdk = "9b6680844e"

[libraries]
accompanist-placeholder-material = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanistPlaceholderMaterial" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityVersion" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityVersion" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-datastore-proto = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3WindowSizeClass" }

androidx-media3-common = { module = "androidx.media3:media3-common", version.ref = "media3Exoplayer" }
androidx-media3-datasource = { module = "androidx.media3:media3-datasource", version.ref = "media3Exoplayer" }
androidx-media3-decoder = { module = "androidx.media3:media3-decoder", version.ref = "media3Exoplayer" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3Exoplayer" }
androidx-media3-exoplayer-workmanager = { module = "androidx.media3:media3-exoplayer-workmanager", version.ref = "media3Exoplayer" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "media3Exoplayer" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingCompose" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "compose" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }

ijkplayer-java = { module = "tv.danmaku.ijk.media:ijkplayer-java", version.ref = "ijkplayer" }
ijkplayer-armv7a = { module = "tv.danmaku.ijk.media:ijkplayer-armv7a", version.ref = "ijkplayer" }
ijkplayer-armv5 = { module = "tv.danmaku.ijk.media:ijkplayer-armv5", version.ref = "ijkplayer" }
ijkplayer-arm64 = { module = "tv.danmaku.ijk.media:ijkplayer-arm64", version.ref = "ijkplayer" }
ijkplayer-x86 = { module = "tv.danmaku.ijk.media:ijkplayer-x86", version.ref = "ijkplayer" }
ijkplayer-x8664 = { module = "tv.danmaku.ijk.media:ijkplayer-x86_64", version.ref = "ijkplayer" }

bilibili-sdk = { module = "com.github.SpaceXC:Bilibili-Kotlin-SDK", version.ref = "bilibili-sdk" }

androidx-material3-window-size = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3WindowSizeClass" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "paletteKtx" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntime" }
appcenter-analytics = { module = "com.microsoft.appcenter:appcenter-analytics", version.ref = "appCenterSdkVersion" }
appcenter-crashes = { module = "com.microsoft.appcenter:appcenter-crashes", version.ref = "appCenterSdkVersion" }
appcompat-v7 = { module = "com.android.support:appcompat-v7", version.ref = "appcompatV7" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coilCompose" }
zoomable = { module = "net.engawapg.lib:zoomable", version.ref = "zoomable" }
crashx = { module = "com.github.TutorialsAndroid:crashx", version.ref = "crashx" }
danmaku-flame-master = { module = "com.github.ctiao:DanmakuFlameMaster", version.ref = "danmakuflamemaster" }
espresso-core = { module = "com.android.support.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
junit = { module = "junit:junit", version.ref = "junitVersion" }
leancloud-storage = { module = "cn.leancloud:storage-android", version.ref = "leancloud" }
runner = { module = "com.android.support.test:runner", version.ref = "runner" }
rxjava-rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxjava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWork" }
hilt-work-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltWork" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
rxhttp = { module = "com.github.liujingxing.rxhttp:rxhttp", version.ref = "rxhttp" }
rxhttp-compiler = { module = "com.github.liujingxing.rxhttp:rxhttp-compiler", version.ref = "rxhttp" }
kotlinx-metadata-jvm = { module = "org.jetbrains.kotlinx:kotlinx-metadata-jvm", version.ref = "kotlinxMetadataJvm" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktorClientCore" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktorClientCore" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorClientCore" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCore" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktorClientCore" }
ktor-serialization-gson = { module = "io.ktor:ktor-serialization-gson", version.ref = "ktorClientCore" }
ktor-serialization-kotlinx-protobuf = { module = "io.ktor:ktor-serialization-kotlinx-protobuf", version.ref = "ktorClientCore" }
material = { module = "com.google.android.material:material", version.ref = "material" }
photoView = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoview" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuflite" }
protobuf-kotlin-lite = { module = "com.google.protobuf:protobuf-kotlin-lite", version.ref = "protobuflite" }
zxing-core = { module = "com.google.zxing:core", version.ref = "coreVersion" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }

[plugins]
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
org-jetbrains-kotlin-atomicfu = { id = "org.jetbrains.kotlin.plugin.atomicfu", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
google-protobuf = { id = "com.google.protobuf", version.ref = "protobuf" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidTest = { id = "com.android.test", version.ref = "agp" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
